name: rust continuous integration
on: 
    pull_request:
        branches:
            - main

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup | Rust
              uses: ATiltedTree/setup-rust@v1
              with:
                  rust-version: 1.26.0
            - name: Run build
              run: cargo build --release
